### ISSUE TITLE
FYI See this repo with clean TD Ameritrade API schemas.

### ISSUE THREAD

**Issue by blais** [sdizazzo/py-ameritrade#4]
https://github.com/blais/ameritrade-api-schemas

**Comment by sdizazzo** [comment]
Thanks.  This stopped me from moving forward and I gave up.  It was my first project after a year off, and looking at it now its really ugly.  Looks like you have something comparable but complete.  I'm working on other things at the moment, and not sure when/if I'll have the time/interest to come back to this.

https://github.com/sdizazzo/py-ameritrade/issues/3

**Comment by blais** [comment]
Yes, it was a bit of a pain to parse and split apart the files from their website. I asked the rep to provide original schemas about a year ago, but they were revamping the API and never got to it. I just got tired and I'm starting to ramp up my trading now so I need it in earnest. You're welcome to use what I got here and build up again (that's why I shared it with you and other similar projects).
